<h3 class="sub-header">سخن روز</h3>
<div class="col-lg-12 col-md-12">
<?php
### GENERATED BY POOYA SABRAMOOZ ###
	
	$quotations_query = "SELECT * FROM quotations ORDER BY RAND() LIMIT 1 ; ";
	$quotations_result = $mysqli->query($quotations_query);	
	$quotations_row = $quotations_result->fetch_assoc();

?>
<blockquote class="blockquote-reverse">
  <p><?php echo $quotations_row['text']; ?></p>
  <footer style="direction:rtl;color:#3399CC"><?php echo $quotations_row['author']; ?></footer>
</blockquote>
</div>